@startwbs
* Organic Farm Temperature and Humidity Sensor based on IOT automation project
** Initialtion
*** Take request
*** Requirement analysis
*** Risk assessment for the project
*** Cost calculation
** Planning
*** Time, human resources
*** Research and finalise the Topic
*** Create Blog
*** Create a Proposal and Plan
** Execution
*** Design
*** Construction
** Evaluation
*** Proof Reading
*** Create Notes
*** Test
*** Report
** losing
*** Result
*** Final Report
*** Final Presentation
@endwbs